// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Context.Migrations
{
    [DbContext(typeof(Db_Context))]
    [Migration("20220303023614_v8")]
    partial class v8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.BPMSysOUMembers", b =>
                {
                    b.Property<int>("Ouid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FGOUEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("FGYWEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LeaderTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("UserAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserDefaultRole")
                        .HasColumnType("bit");

                    b.HasKey("Ouid");

                    b.ToTable("BPMSysOUMembers");
                });

            modelBuilder.Entity("Model.BPMSysOURoles", b =>
                {
                    b.Property<int>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ouid")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyId");

                    b.ToTable("BPMSysOURoles");
                });

            modelBuilder.Entity("Model.BPMSysOUs", b =>
                {
                    b.Property<int>("Ouid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OULevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OUName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ParentOUID")
                        .HasColumnType("int");

                    b.Property<string>("Rsid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ouid");

                    b.ToTable("BPMSysOUs");
                });

            modelBuilder.Entity("Model.BPMSysUsers", b =>
                {
                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hrid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogonProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSpell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SysUser")
                        .HasColumnType("bit");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("WWWHomePage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("家庭电话")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Account");

                    b.ToTable("BPMSysUsers");
                });

            modelBuilder.Entity("Model.ChapterModels", b =>
                {
                    b.Property<int>("Chapter_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chapter_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_Lend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_Part")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_People")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter_SendBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Chapter_Id");

                    b.ToTable("ChapterModels");
                });

            modelBuilder.Entity("Model.Employ", b =>
                {
                    b.Property<int>("employ_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("employ_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Hdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Health")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("employ_Isput")
                        .HasColumnType("bit");

                    b.Property<string>("employ_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("employ_Sex")
                        .HasColumnType("bit");

                    b.Property<string>("employ_Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employ_Id");

                    b.ToTable("Employ");
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Property<int>("employee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("employee_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_Relation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Model.InfoModels", b =>
                {
                    b.Property<int>("info_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("info_April")
                        .HasColumnType("int");

                    b.Property<int>("info_August")
                        .HasColumnType("int");

                    b.Property<int>("info_December")
                        .HasColumnType("int");

                    b.Property<int>("info_February")
                        .HasColumnType("int");

                    b.Property<int>("info_January")
                        .HasColumnType("int");

                    b.Property<int>("info_July")
                        .HasColumnType("int");

                    b.Property<int>("info_June")
                        .HasColumnType("int");

                    b.Property<int>("info_LastYears_Has")
                        .HasColumnType("int");

                    b.Property<int>("info_March")
                        .HasColumnType("int");

                    b.Property<int>("info_May")
                        .HasColumnType("int");

                    b.Property<int>("info_November")
                        .HasColumnType("int");

                    b.Property<int>("info_October")
                        .HasColumnType("int");

                    b.Property<string>("info_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("info_September")
                        .HasColumnType("int");

                    b.Property<int>("info_Sum")
                        .HasColumnType("int");

                    b.HasKey("info_Id");

                    b.ToTable("InfoModels");
                });

            modelBuilder.Entity("Model.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("applyDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("applyDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("applyPeople")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leaveDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leaveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leaveType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("startDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("taskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Leave");
                });

            modelBuilder.Entity("Model.PlanModels", b =>
                {
                    b.Property<int>("plan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("plan_CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("plan_InFormationId")
                        .HasColumnType("int");

                    b.Property<string>("plan_PartMent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plan_People")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plan_Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("plan_Years")
                        .HasColumnType("datetime2");

                    b.HasKey("plan_Id");

                    b.ToTable("PlanModels");
                });

            modelBuilder.Entity("Model.Procurement", b =>
                {
                    b.Property<int>("procurement_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("procurement_Jbu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("procurement_Jing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("procurement_Jtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("procurement_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("procurement_Sbu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("procurement_Stime")
                        .HasColumnType("datetime2");

                    b.Property<string>("procurement_Yong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("procurement_Id");

                    b.ToTable("Procurement");
                });

            modelBuilder.Entity("Model.ProcurementPlus", b =>
                {
                    b.Property<int>("procurementplus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("procurementplus_Bei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("procurementplus_Dan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("procurementplus_Gui")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("procurementplus_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("procurementplus_Num")
                        .HasColumnType("int");

                    b.Property<decimal>("procurementplus_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("procurementplus_Id");

                    b.ToTable("ProcurementPlus");
                });

            modelBuilder.Entity("Model.Reception", b =>
                {
                    b.Property<int>("reception_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("reception_Bei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Bu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Jie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Lai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Laifang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reception_Rnum")
                        .HasColumnType("int");

                    b.Property<string>("reception_Shi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("reception_Stime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("reception_Ttime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("reception_Ttimeplus")
                        .HasColumnType("datetime2");

                    b.Property<bool>("reception_Wu")
                        .HasColumnType("bit");

                    b.Property<string>("reception_Yao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Zhuyao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("reception_Zi")
                        .HasColumnType("bit");

                    b.HasKey("reception_Id");

                    b.ToTable("Reception");
                });

            modelBuilder.Entity("Model.Receptionplus", b =>
                {
                    b.Property<int>("receptionplus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("receptionplus_Bei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptionplus_Bu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("receptionplus_Can")
                        .HasColumnType("bit");

                    b.Property<DateTime>("receptionplus_Etime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("receptionplus_Hui")
                        .HasColumnType("bit");

                    b.Property<bool>("receptionplus_Jiu")
                        .HasColumnType("bit");

                    b.Property<string>("receptionplus_Pei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("receptionplus_Stime")
                        .HasColumnType("datetime2");

                    b.Property<string>("receptionplus_Xing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("receptionplus_Yong")
                        .HasColumnType("bit");

                    b.Property<bool>("receptionplus_Zhan")
                        .HasColumnType("bit");

                    b.HasKey("receptionplus_Id");

                    b.ToTable("Receptionplus");
                });

            modelBuilder.Entity("Model.Receptions", b =>
                {
                    b.Property<int>("receptions_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("receptions_Bei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Ben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Knum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Qin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Snum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("receptions_Id");

                    b.ToTable("Receptions");
                });

            modelBuilder.Entity("Model.RoomNewModel", b =>
                {
                    b.Property<int>("roomnewmodel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("roomnewmodel_Bai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roomnewmodel_Floor")
                        .HasColumnType("int");

                    b.Property<string>("roomnewmodel_Guan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomnewmodel_Kong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomnewmodel_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roomnewmodel_Rnum")
                        .HasColumnType("int");

                    b.Property<string>("roomnewmodel_Tou")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomnewmodel_Wfan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomnewmodel_Wifi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomnewmodel_Ying")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomnewmodel_Zhao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roomnewmodel_Znum")
                        .HasColumnType("int");

                    b.HasKey("roomnewmodel_Id");

                    b.ToTable("RoomNewModel");
                });

            modelBuilder.Entity("Model.RoomreservationModel", b =>
                {
                    b.Property<int>("roomreservationmodel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("roomreservationmodel_Bu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("roomreservationmodel_Etime")
                        .HasColumnType("datetime2");

                    b.Property<string>("roomreservationmodel_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomreservationmodel_People")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roomreservationmodel_Shi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("roomreservationmodel_Stime")
                        .HasColumnType("datetime2");

                    b.Property<int>("roomreservationmodel_Zuo")
                        .HasColumnType("int");

                    b.HasKey("roomreservationmodel_Id");

                    b.ToTable("RoomreservationModel");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("user_Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
