// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Context.Migrations
{
    [DbContext(typeof(Db_Context))]
    partial class Db_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Employ", b =>
                {
                    b.Property<int>("employ_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("employ_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("employ_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("employ_Hdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("employ_Health")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("employ_Isput")
                        .HasColumnType("bit");

                    b.Property<string>("employ_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("employ_Sex")
                        .HasColumnType("bit");

                    b.Property<string>("employ_Speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employ_Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employ_Id");

                    b.ToTable("Employ");
                });

            modelBuilder.Entity("Model.Employee", b =>
                {
                    b.Property<int>("employee_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("employee_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_Post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_Relation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Model.LeaveNew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeaveNew");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("user_Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
