// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Context.Migrations
{
    [DbContext(typeof(Db_Context))]
    partial class Db_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

           

           

            

            modelBuilder.Entity("Model.Reception", b =>
                {
                    b.Property<int>("reception_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("reception_Bei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Bu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Jie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Lai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Laifang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reception_Rnum")
                        .HasColumnType("int");

                    b.Property<string>("reception_Shi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("reception_Stime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("reception_Ttime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("reception_Ttimeplus")
                        .HasColumnType("datetime2");

                    b.Property<bool>("reception_Wu")
                        .HasColumnType("bit");

                    b.Property<string>("reception_Yao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reception_Zhuyao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("reception_Zi")
                        .HasColumnType("bit");

                    b.HasKey("reception_Id");

                    b.ToTable("Reception");
                });

            modelBuilder.Entity("Model.Receptionplus", b =>
                {
                    b.Property<int>("receptionplus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("receptionplus_Bei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptionplus_Bu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("receptionplus_Can")
                        .HasColumnType("bit");

                    b.Property<DateTime>("receptionplus_Etime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("receptionplus_Hui")
                        .HasColumnType("bit");

                    b.Property<bool>("receptionplus_Jiu")
                        .HasColumnType("bit");

                    b.Property<string>("receptionplus_Pei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("receptionplus_Stime")
                        .HasColumnType("datetime2");

                    b.Property<string>("receptionplus_Xing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("receptionplus_Yong")
                        .HasColumnType("bit");

                    b.Property<bool>("receptionplus_Zhan")
                        .HasColumnType("bit");

                    b.HasKey("receptionplus_Id");

                    b.ToTable("Receptionplus");
                });

            modelBuilder.Entity("Model.Receptions", b =>
                {
                    b.Property<int>("receptions_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("receptions_Bei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Ben")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Knum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Qin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receptions_Snum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("receptions_Id");

                    b.ToTable("Receptions");
                });

           
#pragma warning restore 612, 618
        }
    }
}
